# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build todo-express`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t todo-express`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system todo-express && \
          adduser --system -G todo-express todo-express

COPY dist/todo-express todo-express/
RUN chown -R todo-express:todo-express .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix todo-express --omit=dev -f install

CMD [ "node", "todo-express" ]
